language: node_js
node_js:
  - '0.10'

env:
  global:
    secure: qeFyqdmPvt/ZCfN60KDES+o9+3Ebebq4XtAA1sswdN+LnarDescMIGSpNiJrP0rMncnEd78eOz8/R6m4GGcUxKRE/jX1W6buJLO5TJpAoMAK8//EF3I6AvzFvsafGRxt7ZF8xWLEh1c/iDb2zSIOBuT0DQXa3fi0Y+twlTKf90U=

deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: D6VTQ/gzVtYVnYjDbRZzh8SBgPtcO8PVU7LcklLWxvsabuTEg5jro44yW1tfFlhFlB/rH+zRyIwMkbZRsWx8wn0P1Fz0wMuI77oX0AEVtqGUKdGs5l4hApatNxQQGgidJOOvypRy4a7N9Zw8UphkOiyDUwOo65H4YydgjdzZaiA=