language: node_js
node_js:
- iojs
- 0.12
- 0.11
- 0.1
before_script: npm install -g bower
script: npm test
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: D6VTQ/gzVtYVnYjDbRZzh8SBgPtcO8PVU7LcklLWxvsabuTEg5jro44yW1tfFlhFlB/rH+zRyIwMkbZRsWx8wn0P1Fz0wMuI77oX0AEVtqGUKdGs5l4hApatNxQQGgidJOOvypRy4a7N9Zw8UphkOiyDUwOo65H4YydgjdzZaiA=
