# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
before_install:
  - npm install coffee-script --global
  - npm install bower --global
language: node_js
node_js:
  - '0.10'

# COVERALLS_REPO_TOKEN
env:
  global:
    secure: qeFyqdmPvt/ZCfN60KDES+o9+3Ebebq4XtAA1sswdN+LnarDescMIGSpNiJrP0rMncnEd78eOz8/R6m4GGcUxKRE/jX1W6buJLO5TJpAoMAK8//EF3I6AvzFvsafGRxt7ZF8xWLEh1c/iDb2zSIOBuT0DQXa3fi0Y+twlTKf90U=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: VCZOseyR+gFOH1qaeXitmK5MVQAgjb/Jh+UjupAl/A1o8uCysXW2cKrG4Fe2m60gqYHGxpUqAyi93iD2yNmvvUApt+ODC0KDaPrX+ZKI5mEE23SfubfAVKKAhKD/JS/FczgP73QKxlMblNyrUonf60LGunGfom3ZTxELqaQBVEE=
  on:
    repo: 59naga/onefile
