# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
before_install:
  - npm install coffee-script --global
  - npm install bower --global
language: node_js
node_js:
  - '0.10'

# COVERALLS_REPO_TOKEN
env:
  global:
    secure: qeFyqdmPvt/ZCfN60KDES+o9+3Ebebq4XtAA1sswdN+LnarDescMIGSpNiJrP0rMncnEd78eOz8/R6m4GGcUxKRE/jX1W6buJLO5TJpAoMAK8//EF3I6AvzFvsafGRxt7ZF8xWLEh1c/iDb2zSIOBuT0DQXa3fi0Y+twlTKf90U=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: a5cJQcEX18Yi48rFB0QWMSmcljYZ7qBcAIM71QZVucMLGJh75EcrAMgvBhC3SEo3FF4xySj4aA92DXrUcJt1NLyhf0GGlkjYEEccAcgmPDEFDng5xGrukKFGlCvhcnrpRuh6M/cK+RhWRr3Qq/+Iue9wU4WMZdZshTC2YUDrwqM=
